async function main() {
  
}


main()
  .catch((err) => console.log(err))
  .finally(() => process.exit(0));
